-- Core domain schema. Primary keys are UUIDs generated by the application
-- (Hibernate's GenerationType.UUID), not the database, so no default/extension
-- is needed on the id columns.

CREATE TABLE organisations (
    id         UUID PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    org_id        UUID         NOT NULL REFERENCES organisations (id),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    UUID,
    CONSTRAINT uq_users_org_email UNIQUE (org_id, email)
);
CREATE INDEX idx_users_org_id ON users (org_id);

CREATE TABLE roles (
    id   UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE permissions (
    id   UUID PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE role_permissions (
    role_id       UUID        NOT NULL REFERENCES roles (id),
    permission_id UUID        NOT NULL REFERENCES permissions (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

CREATE TABLE user_roles (
    user_id    UUID        NOT NULL REFERENCES users (id),
    role_id    UUID        NOT NULL REFERENCES roles (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

CREATE TABLE courses (
    id               UUID PRIMARY KEY,
    org_id           UUID         NOT NULL REFERENCES organisations (id),
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    duration_hours   INTEGER      NOT NULL,
    validity_months  INTEGER      NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID
);
CREATE INDEX idx_courses_org_id ON courses (org_id);

CREATE TABLE enrolments (
    id           UUID PRIMARY KEY,
    org_id       UUID        NOT NULL REFERENCES organisations (id),
    course_id    UUID        NOT NULL REFERENCES courses (id),
    user_id      UUID        NOT NULL REFERENCES users (id),
    status       VARCHAR(20) NOT NULL,
    enrolled_at  TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    version      BIGINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by   UUID
);
CREATE INDEX idx_enrolments_org_id ON enrolments (org_id);
CREATE INDEX idx_enrolments_course_id ON enrolments (course_id);
CREATE INDEX idx_enrolments_user_id ON enrolments (user_id);

CREATE TABLE certifications (
    id               UUID PRIMARY KEY,
    org_id           UUID          NOT NULL REFERENCES organisations (id),
    user_id          UUID          NOT NULL REFERENCES users (id),
    course_id        UUID          NOT NULL REFERENCES courses (id),
    issued_at        TIMESTAMPTZ   NOT NULL,
    expires_at       TIMESTAMPTZ   NOT NULL,
    certificate_url  VARCHAR(1024),
    status           VARCHAR(20)   NOT NULL,
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       UUID
);
CREATE INDEX idx_certifications_org_id ON certifications (org_id);
CREATE INDEX idx_certifications_user_id ON certifications (user_id);
CREATE INDEX idx_certifications_course_id ON certifications (course_id);
-- Backs the Phase 6 "certifications expiring soon" / "lapsed" scheduled job queries.
CREATE INDEX idx_certifications_expires_status ON certifications (expires_at, status);
